//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Franka
{
    [Serializable]
    public class TargetStatusMsg : Message
    {
        public const string k_RosMessageName = "franka_msgs/TargetStatus";
        public override string RosMessageName => k_RosMessageName;

        // # The status of a motion action
        //  IDLE: The robot is idle, no motion is being executed
        public const byte IDLE = 0;
        //  EXECUTING: The robot is currently executing the motion
        public const byte EXECUTING = 1;
        //  TARGET_REACHED: The robot has reached the target position given two conditions:
        //  - the absolute difference between the current and goal joint positions is within the goal_tolerance
        //  - the joint velocities are below a small threshold
        public const byte TARGET_REACHED = 2;
        //  ABORTED: The motion was aborted due to an error or external intervention
        public const byte ABORTED = 3;
        // # The current status of the motion (one of the above states)
        public byte status;

        public TargetStatusMsg()
        {
            this.status = 0;
        }

        public TargetStatusMsg(byte status)
        {
            this.status = status;
        }

        public static TargetStatusMsg Deserialize(MessageDeserializer deserializer) => new TargetStatusMsg(deserializer);

        private TargetStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "TargetStatusMsg: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
